#!/bin/bash

# AUFS filesystem support
sudo apt-get update
sudo apt-get install linux-image-extra-`uname -r`


sudo apt-get install software-properties-common

# add PPA for docker from dotcloud
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com E61D797F63561DC6
sudo add-apt-repository -y ppa:dotcloud/lxc-docker

# update
sudo apt-get update

# install
sudo apt-get install lxc-docker
