#!/bin/bash

set -e

# AUFS filesystem support
sudo apt-get -y update
sudo apt-get -y install linux-image-extra-`uname -r`


sudo apt-get install software-properties-common

# add PPA for docker from dotcloud
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com E61D797F63561DC6
sudo add-apt-repository -y ppa:dotcloud/lxc-docker

# update
sudo apt-get -y update

# install
sudo apt-get -y install lxc-docker

# install git
sudo apt-get -y install git

# get godeb
mkdir godeb && cd godeb
curl -L https://godeb.s3.amazonaws.com/godeb-amd64.tar.gz \
    | tar zxf -
./godeb install
cd ..
/bin/rm -rf godeb

# install a few docker images
docker pull base
docker pull ubuntu
docker pull centos
#docker pull wdtz/scientific-6-x86
#docker pull wdtz/scientific-6-x64
#docker pull rahulg/arch
#docker pull schmidh/arch-base
#docker pull jtang/scientificlinux-6.4-x86_64

docker pull binet/slc6-64
docker pull binet/archlinux-64

